spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      primary:
        url: jdbc:mysql://192.168.194.148:3306/test1?serverTimezone=UTC
        username: root
        password: 123456
      secondary:
        url: jdbc:mysql://192.168.194.148:3306/test0?serverTimezone=UTC
        username: root
        password: 123456